"""
GrowthBot implementation.

This module provides the GrowthBot agent that generates A/B testing plans
and growth strategies for portfolio companies.
"""

import os
import json
import uuid
import logging
from datetime import datetime
from typing import Dict, Any, Optional, List

from ..base_agent import BaseAgent
from ..config import GROWTH_PLANS_DIR

# Email signature for all outgoing messages
EMAIL_SIGNATURE = """
<br><br>
Best regards,<br>
GrowthBot<br>
AI.VC Growth Team<br>
"""


class GrowthBot(BaseAgent):
    """
    GrowthBot - AI-powered growth strategist for portfolio companies.
    
    This agent generates A/B testing plans and growth strategies for
    portfolio companies based on their specific business metrics and goals.
    """
    
    async def process_message(self, message: Dict[str, Any]) -> bool:
        """
        Process a growth request message.
        
        Args:
            message: The message containing growth goals and metrics
            
        Returns:
            True if the processing was successful, False otherwise
        """
        self.logger.info(f"Processing growth request for {message.get('company_name', 'Unknown Company')}")
        
        try:
            # Validate the message
            required_fields = ['company_name', 'company_email', 'growth_goal']
            if not all(field in message for field in required_fields):
                self.logger.error(f"Missing required fields in message: {required_fields}")
                return False
            
            # Generate the A/B test plan
            ab_test_plan = self._generate_ab_test_plan(message)
            
            # Save the plan to a file
            plan_id = ab_test_plan.get('test_id')
            plan_path = os.path.join(GROWTH_PLANS_DIR, f"ab_test_{plan_id}.json")
            os.makedirs(GROWTH_PLANS_DIR, exist_ok=True)
            
            with open(plan_path, 'w') as f:
                json.dump(ab_test_plan, f, indent=2)
                
            self.logger.info(f"Saved AB test plan to {plan_path}")
            
            # Send an email with the plan
            await self._send_plan_email(message, ab_test_plan)
            
            return True
            
        except Exception as e:
            self.logger.error(f"Error processing growth request: {str(e)}")
            return False
    
    def _generate_ab_test_plan(self, message: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate an A/B test plan based on the company's growth goals.
        
        In a real implementation, this would use OpenAI to generate the plan.
        For this exercise, we'll create a template.
        
        Args:
            message: The message containing growth goals and metrics
            
        Returns:
            A dictionary containing the A/B test plan
        """
        company_name = message.get('company_name', 'Unknown Company')
        company_id = message.get('company_id', str(uuid.uuid4()))
        growth_goal = message.get('growth_goal', 'increase metrics')
        business_type = message.get('business_type', 'saas')
        focus_area = message.get('focus_area', 'acquisition')
        timeframe = message.get('timeframe', '3 months')
        
        # In a real implementation, this would be generated by OpenAI
        # For this exercise, we'll use a template
        test_id = str(uuid.uuid4())
        created_at = datetime.now().isoformat()
        
        # Calculate expected improvement based on growth goal
        # For example, "increase MRR by 30%" -> 30%
        import re
        expected_improvement = "15%"  # Default
        match = re.search(r'by\s+(\d+)%', growth_goal)
        if match:
            percentage = match.group(1)
            expected_improvement = f"{percentage}%"
        
        if business_type == 'saas':
            if focus_area == 'acquisition':
                test_name = "Product-Led Growth Call-to-action Optimization"
                primary_metric = "Conversion Rate"
                hypothesis = f"By optimizing our call-to-action buttons, we can increase {primary_metric} by {expected_improvement}"
                variations = [
                    {
                        "id": "A",
                        "name": "Control",
                        "description": "Current implementation without changes"
                    },
                    {
                        "id": "B",
                        "name": "Variation B",
                        "description": "Test call-to-action buttons with optimized design"
                    },
                    {
                        "id": "C",
                        "name": "Variation C",
                        "description": "Test call-to-action buttons with enhanced messaging"
                    }
                ]
            else:
                test_name = "User Retention Email Sequence"
                primary_metric = "Churn Rate"
                hypothesis = f"By improving our onboarding email sequence, we can reduce {primary_metric} by {expected_improvement}"
                variations = [
                    {
                        "id": "A",
                        "name": "Control",
                        "description": "Current email sequence"
                    },
                    {
                        "id": "B",
                        "name": "Variation B",
                        "description": "Enhanced email sequence with better onboarding"
                    }
                ]
        else:
            test_name = "Checkout Flow Optimization"
            primary_metric = "Cart Abandonment Rate"
            hypothesis = f"By simplifying the checkout flow, we can reduce {primary_metric} by {expected_improvement}"
            variations = [
                {
                    "id": "A",
                    "name": "Control",
                    "description": "Current checkout flow"
                },
                {
                    "id": "B",
                    "name": "Variation B",
                    "description": "Simplified checkout flow with fewer steps"
                }
            ]
        
        # Create the plan
        return {
            "company_id": company_id,
            "company_name": company_name,
            "test_id": test_id,
            "test_name": test_name,
            "created_at": created_at,
            "business_type": business_type,
            "focus_area": focus_area,
            "growth_goal": growth_goal,
            "hypothesis": hypothesis,
            "primary_metric": primary_metric,
            "secondary_metrics": ["Click-Through Rate", "Sign-Up Rate"],
            "expected_improvement": expected_improvement,
            "duration": "14 days",
            "traffic_allocation": {
                "control": 50,
                "variations": 50
            },
            "variations": variations,
            "implementation_details": {
                "test_pages": ["Homepage", "Product Page", "Checkout Flow"],
                "user_segments": ["All Users", "New Visitors", "Returning Visitors"],
                "technical_requirements": [
                    "Implement tracking for all variations",
                    "Ensure proper A/B test bucketing",
                    "Set up analytics dashboard for monitoring"
                ]
            },
            "success_criteria": {
                "statistical_significance": "95% confidence level",
                "minimum_sample_size": "Calculated based on expected improvement",
                "decision_framework": "Winner determined by primary metric improvement with statistical significance"
            }
        }
    
    async def _send_plan_email(self, message: Dict[str, Any], ab_test_plan: Dict[str, Any]) -> bool:
        """
        Send an email with the A/B test plan.
        
        Args:
            message: The original message
            ab_test_plan: The generated A/B test plan
            
        Returns:
            True if the email was sent successfully, False otherwise
        """
        company_name = message.get('company_name', 'Unknown Company')
        company_email = message.get('company_email')
        
        if not company_email:
            self.logger.error("No email address provided in message")
            return False
        
        subject = f"Growth Strategy: A/B Test Plan for {company_name}"
        
        # Create the email body
        body = f"""
        <html>
        <body>
        <h2>A/B Test Plan for {company_name}</h2>
        
        <p>Dear {company_name} team,</p>
        
        <p>Based on your growth goal to <strong>{ab_test_plan.get('growth_goal')}</strong>,
        we've prepared an A/B testing plan to help you achieve your objectives.</p>
        
        <h3>Test Overview</h3>
        <ul>
            <li><strong>Test Name:</strong> {ab_test_plan.get('test_name')}</li>
            <li><strong>Hypothesis:</strong> {ab_test_plan.get('hypothesis')}</li>
            <li><strong>Primary Metric:</strong> {ab_test_plan.get('primary_metric')}</li>
            <li><strong>Expected Improvement:</strong> {ab_test_plan.get('expected_improvement')}</li>
            <li><strong>Duration:</strong> {ab_test_plan.get('duration')}</li>
        </ul>
        
        <h3>Variations</h3>
        <ul>
        """
        
        for variation in ab_test_plan.get('variations', []):
            body += f"""
            <li><strong>{variation.get('name')}:</strong> {variation.get('description')}</li>
            """
            
        body += f"""
        </ul>
        
        <h3>Implementation Details</h3>
        <p><strong>Test Pages:</strong> {', '.join(ab_test_plan.get('implementation_details', {}).get('test_pages', []))}</p>
        <p><strong>User Segments:</strong> {', '.join(ab_test_plan.get('implementation_details', {}).get('user_segments', []))}</p>
        
        <h3>Technical Requirements</h3>
        <ul>
        """
        
        for req in ab_test_plan.get('implementation_details', {}).get('technical_requirements', []):
            body += f"<li>{req}</li>"
            
        body += f"""
        </ul>
        
        <p>The full A/B test plan is attached to this email as a JSON file. You can import this
        plan into your testing tool or review it with your development team.</p>
        
        <p>If you have any questions or need assistance implementing this plan, please don't
        hesitate to reply to this email.</p>
        
        {EMAIL_SIGNATURE}
        </body>
        </html>
        """
        
        return await self.send_email(company_email, subject, body)